Repository jumperexchange/jumper-exchange, pull requests merged in 2023-10, with the labels that each got.

#667 feat: add lifi-explorer to main-menu
  packages/dapp/src/const/MenuConfig/useMainMenuContent.tsx
  packages/dapp/src/i18n/en/translation.json
Labels: wait, testing

#696 fix: updated yarn.lock
  yarn.lock
Labels: testing

#700 chore: bump packages
  package.json
  packages/dapp/package.json
  packages/shared/package.json
  yarn.lock
Labels: testing

#698 Production Release
  package.json
  packages/dapp/package.json
  packages/shared/package.json
  yarn.lock
Labels: wait

#687 fix: check installed wallets on wallet selection
  packages/dapp/src/components/Navbar/Menu/Menus.tsx
  packages/dapp/src/components/Navbar/Menu/WalletMenu/WalletMenu.tsx
  packages/dapp/src/const/MenuConfig/useWalletSelectContent.tsx
  packages/dapp/src/i18n/en/translation.json
  packages/dapp/src/stores/menu/MenuStore.tsx
  packages/dapp/src/stores/settings/SettingsStore.tsx
  packages/shared/src/config.ts
  packages/shared/src/theme/theme.ts
  packages/shared/src/types/menu.ts
  packages/shared/src/types/settings.ts
Labels: testing
