Repository jumperexchange/jumper-exchange, pull requests merged in 2024-06, with the labels that each got.

#1012 feat: add more public rpc endpoints and randomize order
  .env.development
  .env.production
  .env.staging
  new-types.d.ts
  src/app/global-error.tsx
  src/components/Widgets/Widget.tsx
  src/const/rpcList.ts
  src/utils/shuffleArray.ts
Labels: feature

#990 feat: add support for api_key with env_var
  .env.development
  .env.localhost
  .env.production
  .env.staging
  src/components/Widgets/Widget.tsx
Labels: feature

#1017 chore: new Crowdin updates
  i18nconfig.ts
  src/i18n/translations/id/translation.json
  src/i18n/translations/index.ts
  src/i18n/translations/ja/language.json
  src/i18n/translations/ja/translation.json
  src/i18n/translations/vi/translation.json
Labels: wait

#1031 feat: enable Rootstock on Gas tab
  src/components/Widgets/Widget.types.ts
Labels: feature

#1013 style: improve the UI on mobile
  src/app/[lng]/learn/[slug]/page.tsx
  src/app/[lng]/learn/page.tsx
  src/app/[lng]/profile/page.tsx
  src/app/not-found.tsx
  src/components/BackgroundGradient/BackgroundGradient.style.tsx
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/NavbarButtons/NavbarButtons.tsx
  src/components/Navbar/NavbarButtons/WalletManagementButtons.style.ts
  src/components/Navbar/NavbarButtons/WalletManagementButtons.tsx
  src/components/PoweredBy/PoweredBy.style.ts
  src/components/WelcomeScreen/ToolCard/ToolCards.style.ts
  src/components/WelcomeScreen/WelcomeScreen.style.ts
  src/components/Widgets/Widget.style.ts
  src/components/Widgets/Widget.tsx
  src/components/Widgets/WidgetSkeleton.style.ts
  src/components/Widgets/Widgets.style.tsx
Labels: testing, wip, feature

#1036 fix: subtitle color
  src/components/FeatureCards/FeatureCard.style.tsx
Labels: feature

#1039 fix: feature-card typography colors
  src/components/FeatureCards/FeatureCard.style.tsx
  src/components/FeatureCards/FeatureCard.tsx
Labels: feature

#1048 feat: add important message for Metamask
  next.config.mjs
  src/Layout.tsx
Labels: feature

#1021 feat: add session id
  package.json
  src/app/ui/learn/LearnArticlePage.tsx
  src/components/Blog/FeaturedArticle/FeaturedArticle.tsx
  src/components/ProfilePage/ProfilePage.tsx
  src/components/Widgets/Widgets.tsx
  src/hooks/useSession.ts
  yarn.lock
Labels: testing, feature

#1051 fix: reference error session-storage
  src/components/FeatureCards/FeatureCards.tsx
  src/hooks/useSession.ts
Labels: testing, feature

#1023 refacto: Optimize loading
  package.json
  src/app/[lng]/buy/page.tsx
  src/app/[lng]/exchange/page.tsx
  src/app/[lng]/gas/page.tsx
  src/app/[lng]/layout.tsx
  src/app/[lng]/memecoins/page.tsx
  src/app/[lng]/page.tsx
  src/app/ui/app/App.style.ts
  src/app/ui/app/App.tsx
  src/components/FeatureCards/FeatureCard.tsx
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/NavbarButtons/NavbarButtons.tsx
  src/components/Navbar/NavbarTabs/useNavbarTabs.tsx
  src/components/OnRamper/OnRamper.tsx
  src/components/Tabs/Tabs.tsx
  src/components/WelcomeScreen/WelcomeScreen.style.ts
  src/components/WelcomeScreen/WelcomeScreen.tsx
  src/components/Widgets/Widget.style.ts
  src/components/Widgets/Widget.tsx
  src/components/Widgets/WidgetSkeleton.tsx
  src/components/Widgets/Widgets.style.tsx
  src/components/Widgets/Widgets.tsx
  src/hooks/useWelcomeScreen.ts
  yarn.lock
Labels: testing, feature

#1044 feat: partner url that filter on a specific partner
  src/app/[lng]/[partnerTheme]/page.tsx
  src/app/[lng]/learn/page.tsx
  src/app/[lng]/memecoins/page.tsx
  src/components/BackgroundGradient/BackgroundGradient.tsx
  src/components/Widgets/Widget.tsx
  src/components/Widgets/Widget.types.ts
  src/components/Widgets/Widgets.tsx
  src/hooks/useDexsAndBridgesKeys.tsx
  src/hooks/usePartnerTheme.ts
  src/types/internal.ts
Labels: feature
